version: '3.9'
services:
  ms-usuarios:
    build: ./ms-usuarios
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - DB_HOST=cockroach-1
      - DB_PORT=26257
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=usuarios
      - DB_SSL=false
      - JWT_SECRET=super_secreto
    depends_on:
      - cockroach-1
  ms-reservas:
    build: ./ms-reservas
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=cockroach-1
      - DB_PORT=26257
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=reservas
      - DB_SSL=false
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq
      - RABBITMQ_QUEUE=reserva_confirmada
      - JWT_SECRET=super_secreto
    depends_on:
      - cockroach-1
      - rabbitmq

  ms-notificaciones:
    build: ./ms-notificaciones
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq
      - RABBITMQ_QUEUE=qr_generado
      - EMAIL_FROM=no-reply@encuentro.com
    depends_on:
      - rabbitmq

  ms-entradas:
    build: ./ms-entradas
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - DB_HOST=cockroach-1
      - DB_PORT=26257
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=entradas
      - DB_SSL=false
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq
      - RABBITMQ_IN_QUEUE=reserva_confirmada
      - RABBITMQ_OUT_QUEUE=qr_generado
    depends_on:
      - rabbitmq
      - cockroach-1

  ms-conciertos:
    build: ./ms-conciertos
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - DB_HOST=cockroach-1
      - DB_PORT=26257
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=conciertos
      - DB_SSL=false
      - JWT_SECRET=super_secreto
    depends_on:
      - cockroach-1

  cockroach-1:
    image: cockroachdb/cockroach:v23.1.11
    command: start --insecure --join=cockroach-1,cockroach-2,cockroach-3
    volumes:
      - cockroach-data-1:/cockroach/cockroach-data
    ports:
      - "26257:26257"
      - "8080:8080"

  cockroach-2:
    image: cockroachdb/cockroach:v23.1.11
    command: start --insecure --join=cockroach-1,cockroach-2,cockroach-3
    volumes:
      - cockroach-data-2:/cockroach/cockroach-data

  cockroach-3:
    image: cockroachdb/cockroach:v23.1.11
    command: start --insecure --join=cockroach-1,cockroach-2,cockroach-3
    volumes:
      - cockroach-data-3:/cockroach/cockroach-data

  init-cluster:
    image: cockroachdb/cockroach:v23.1.11
    depends_on:
      - cockroach-1
      - cockroach-2
      - cockroach-3
    command: init --insecure --host=cockroach-1

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # UI en http://localhost:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  kong-db:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-db-data:/var/lib/postgresql/data

  kong-migrations:
    image: kong:3.6
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    depends_on:
      - kong-db

  kong:
    image: kong:3.6
    depends_on:
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000" # API Gateway
      - "8001:8001" # Admin API
      - "8443:8443"
      - "8444:8444"

  konga:
    image: pantsel/konga
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=development
    depends_on:
      - kong

volumes:
  cockroach-data-1:
  cockroach-data-2:
  cockroach-data-3:
  kong-db-data:
